# Generated by Django 4.0.2 on 2022-02-14 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_actormovie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='downvote',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='upvote',
            field=models.IntegerField(default=0),
        ),
    ]
