# Generated by Django 4.0.2 on 2022-02-16 07:36

from __future__ import unicode_literals

from django.db import migrations, models


def insertData(apps, schema_editor):
    Movie = apps.get_model('base', 'Movie')
    user = Movie(title="Zombieland", release_date="2012-12-04",
                 description="Horror and comedy", upvote=0, downvote=0)
    user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_movie_downvote_movie_upvote'),
    ]

    operations = [
        migrations.RunPython(insertData),
    ]
